import environs

__all__ = (
    "SECRET_KEY", "ALLOWED_HOSTS", "CORS_ALLOWED_ORIGINS", "CSRF_TRUSTED_ORIGINS", "EMAIL_HOST", "EMAIL_PORT",
    "EMAIL_HOST_USER", "EMAIL_HOST_PASSWORD", "DJANGO_SUPERUSER_EMAIL", "DJANGO_SUPERUSER_PASSWORD",
    "OFFSET_TIMEZONE", "LENGTH_CONFIRM_CODE", "INTERVAL_CONFIRM_CODE_IN_SECONDS", "INTERVAL_API_TOKEN_IN_SECONDS",
    "MIN_DISTANCE_BETWEEN_POINTS", "COORD_ROUND_SCALE"
)

env = environs.Env()
env.read_env()
SECRET_KEY = env.str('SECRET_KEY').encode('UTF-8')
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')

CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS')
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS')

EMAIL_HOST = env.str('EMAIL_HOST')
EMAIL_PORT = env.str('EMAIL_PORT')
EMAIL_HOST_USER = env.str('EMAIL_USER')
EMAIL_HOST_PASSWORD = env.str('EMAIL_PASSWORD')

DJANGO_SUPERUSER_EMAIL = env.str('DJANGO_SUPERUSER_EMAIL')
DJANGO_SUPERUSER_PASSWORD = env.str('DJANGO_SUPERUSER_PASSWORD')

OFFSET_TIMEZONE = 3
LENGTH_CONFIRM_CODE = 6
INTERVAL_CONFIRM_CODE_IN_SECONDS = 200
INTERVAL_API_TOKEN_IN_SECONDS = 18000
MIN_DISTANCE_BETWEEN_POINTS = 100
COORD_ROUND_SCALE = 8
