# Generated by Django 5.0.6 on 2024-08-30 09:29

from django.db import migrations
from pathlib import Path


def load_data_from_sql(filename):
    file_path = Path(__file__).resolve().parent.joinpath("sql_scripts", filename)
    sql_statement = open(file_path, encoding="UTF-8").read()
    return sql_statement


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(sql=load_data_from_sql("MigrateFederalDistricts.sql")),
        migrations.RunSQL(sql=load_data_from_sql("MigrateFederalSubjects.sql")),
    ]
